env_name: 'Hopper-v4'
env_parameters:
  ctrl_cost_weight: 0.075

# from ddpg.yaml (exercise 6)
agent_name: ddpg    

train_episodes: 3000
gamma: 0.99
lr: 3e-4
tau: 0.005
batch_size: 256
buffer_size: 1e6

seed: 300
exp_name: ex6
run_id: ??? # decided during execution

testing: true
model_path: default

save_video: false
save_logging: true
save_model: true
use_wandb: true
silent: false

max_episode_steps: 1000
grad_clip_norm: 1
random_episodes: 10

hidden_dims: [64, 64]
glie_b: 200

run_suffix: 0
# ref: https://stackoverflow.com/questions/65104134/disable-file-output-of-hydra
hydra:  
    output_subdir: null  
    run:  
        dir: .
