env_name: 'Hopper-v4'
env_parameters:
  ctrl_cost_weight: 0.075

# from ddpg.yaml (exercise 6)
agent_name: NAF  

train_episodes: 5000
gamma: 0.99
lr: 1e-3
tau: 0.005
batch_size: 256
buffer_size: 1e6

seed: 408
exp_name: ex6
run_id: ??? # decided during execution

testing: false
model_path: default

save_video: false
save_logging: true
save_model: true
use_wandb: true
silent: false

max_episode_steps: 2000
grad_clip_norm: 1.0
random_episodes: 10

hidden_dims: 256
glie_b: 200

run_suffix: 0
# ref: https://stackoverflow.com/questions/65104134/disable-file-output-of-hydra
hydra:  
    output_subdir: null  
    run:  
        dir: .
