env_name: 'LunarLander-v2'
env_parameters:
  continuous: true
  gravity: -9.81
  enable_wind: true
  wind_power: 15
  turbulence_power: 1.5

agent_name: naf   

train_episodes: 3000
gamma: 0.99
lr: 3e-4
tau: 0.005
batch_size: 256
buffer_size: 1e6

seed: 300
exp_name: ex6
run_id: ??? # decided during execution

testing: true
model_path: default

save_video: true
save_logging: true
save_model: true
use_wandb: true
silent: false

max_episode_steps: 1000
grad_clip_norm: 1
random_episodes: 10

hidden_dims: [64, 64]
glie_b: 200

run_suffix: 0
# ref: https://stackoverflow.com/questions/65104134/disable-file-output-of-hydra
hydra:  
    output_subdir: null  
    run:  
        dir: .